FROM ubuntu:21.10

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y nginx supervisor openssl
RUN apt-get install -y python3-pip

RUN openssl req -x509 -nodes -days 365 -subj "/C=RU/ST=Tatarstan/L=Kazan/O=school21/OU=school21/CN=kreinhar" \
    -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt;

ADD . /project/
RUN pip install -r /project/requirement.txt
RUN python3 /project/manage.py migrate


COPY /nginx_conf/nginx.conf  /etc/nginx/sites-available/default
COPY /utils/supervisor.conf /etc/supervisor/conf.d/
COPY /project/utils/django_gunicorn.sock /etc/systemd/system/django_gunicorn.sock

EXPOSE 80
EXPOSE 443

CMD ["supervisord", "-n"]