version: '3.9'

services:
  django:
    image: matakov/yamdb:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/code/nginx/
    entrypoint: /code/entrypoint.sh
  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf/nginx:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always

volumes:
  static:
  media:
  utils: