# Generated by Django 4.0.4 on 2022-05-24 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='negative',
            field=models.IntegerField(default=0, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='tip',
            name='positive',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.tip', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.tip', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
    ]
