# Generated by Django 4.0.4 on 2022-05-25 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex', '0002_tip_negative_tip_positive_upvote_downvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together={('user', 'tip')},
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('user', 'tip')},
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
